// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjktmiwlmlkxixqpjowm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indqa3RtaXdsbWxreGl4cXBqb3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NTIxOTIsImV4cCI6MjA2MTMyODE5Mn0.HlUzsw2GdesYCt0j2xd7ubJtM6QMTid4C7wU9ZPqvBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);